#!/usr/bin/env python3
"""How much of mini's deficit could be context overflow?

For the canonical run-1 cells, count tasks whose trial hit context_overflow, how many of those
also failed, and how many of those overflow-and-fail tasks were solved in run 1 by at least one
of the other two harnesses.  The last count is an upper bound on what a longer context window
could have bought mini: tasks nobody solved are not evidence of a harness effect.

Run: python3 analysis/overflow_bound.py
  -> paper/latex/numbers_ovf.tex, paper/overflow_bound.json
"""
import csv, os, sys, json

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import main_table as mt
import paper_numbers as pn

RUN1, RUN2 = 1, 2
MODELS = {"qwen38": "qwen3.8-27b", "qwen36": "qwen3.6-35b-a3b"}
SUBSETS = ["hard45", "pool447"]
DENOM = {"hard45": 45, "pool447": 447}
SHORT = {"claude-code": "CC", "mini-swe-agent": "mini", "opencode": "OC"}

rows = list(csv.DictReader(open(os.path.join(HERE, "..", "data", "trials.csv"))))
cells = pn.canonical_by_seed(rows)


def overflowed(r):
    return (r.get("context_overflow") or "").strip() in ("1", "True", "true", "TRUE")


def arm_run(model, subset, harness, sd):
    """(label, {task: row}) for the canonical column of this harness at run sd, or (None, {})."""
    lab, c = pn.pick_arm(cells, model, subset, harness)
    if c is None:
        return None, {}
    return lab, mt.usable(c.get(sd, {}))


def analyse(model, subset, harness, sd=RUN1):
    lab, d = arm_run(model, subset, harness, sd)
    if not d:
        return None
    others = {}
    for h in pn.HARNESSES:
        if h == harness:
            continue
        ol, od = arm_run(model, subset, h, sd)
        if od:
            others[ol] = od
    ovf = sorted(t for t, r in d.items() if overflowed(r))
    fail = [t for t in ovf if not pn.is_pass(d[t])]
    elsewhere = {t: sorted(ol for ol, od in others.items() if t in od and pn.is_pass(od[t]))
                 for t in fail}
    elsewhere = {t: v for t, v in elsewhere.items() if v}
    return dict(label=lab, n_tasks=len(d), n=len(ovf), fail=len(fail), elsewhere=len(elsewhere),
                ovf_tasks=ovf, fail_tasks=fail, elsewhere_tasks=elsewhere,
                others=sorted(others))


macros, report = {}, {}
for key, model in MODELS.items():
    for subset in SUBSETS:
        for h in pn.HARNESSES:
            res = analyse(model, subset, h)
            if res is None:
                print(f"{key:7s} {subset:8s} {SHORT[h]:5s}  (no canonical run-1 arm)")
                continue
            report[f"{key}.{subset}.{SHORT[h]}"] = res
            print(f"{key:7s} {subset:8s} {SHORT[h]:5s} [{res['label']}] tasks={res['n_tasks']:3d} "
                  f"overflow={res['n']:3d} overflow&fail={res['fail']:3d} "
                  f"passed by {'/'.join(res['others']) or '-'}={res['elsewhere']:3d}")
            if h != "mini-swe-agent":
                continue
            base = f"ovf.{key}.{subset}.mini"
            macros[f"{base}.n"] = res["n"]
            macros[f"{base}.fail"] = res["fail"]
            macros[f"{base}.elsewhere"] = res["elsewhere"]
            macros[f"{base}.elsewhere.pp"] = f"{100 * res['elsewhere'] / DENOM[subset]:.1f}"

# does the overflow-and-fail set repeat?  run 2 of Qwen3.8 mini on hard45
r1 = report.get("qwen38.hard45.mini")
lab2, d2 = arm_run(MODELS["qwen38"], "hard45", "mini-swe-agent", RUN2)
if r1 and d2:
    present = [t for t in r1["fail_tasks"] if t in d2]
    again = [t for t in present if overflowed(d2[t])]
    passed = [t for t in present if pn.is_pass(d2[t])]
    macros["ovf.qwen38.hard45.mini.run2.present"] = len(present)
    macros["ovf.qwen38.hard45.mini.run2.again"] = len(again)
    macros["ovf.qwen38.hard45.mini.run2.passed"] = len(passed)
    report["qwen38.hard45.mini.run2"] = dict(label=lab2, present=len(present), again=len(again),
                                             passed=len(passed), present_tasks=present,
                                             again_tasks=again, passed_tasks=passed)
    print(f"\nqwen38 hard45 mini run 2 [{lab2}]: of {len(r1['fail_tasks'])} run-1 overflow-and-fail "
          f"tasks, {len(present)} have a usable run-2 trial, {len(again)} overflowed again, "
          f"{len(passed)} passed")
else:
    print("\nqwen38 hard45 mini: no run 2, run-2 macros not written")

with open(os.path.join(HERE, "..", "paper", "latex", "numbers_ovf.tex"), "w") as f:
    f.write("% generated by analysis/overflow_bound.py\n")
    for k, v in sorted(macros.items()):
        f.write(f"\\expandafter\\def\\csname pn@{k}\\endcsname{{{v}}}\n")
json.dump(report, open(os.path.join(HERE, "..", "paper", "overflow_bound.json"), "w"), indent=1)
print("macros:", len(macros))
