#!/usr/bin/env python3
"""Appendix tables A1 / A2 / A10 from data/trials.csv.

Nothing is re-derived here: the canonical-trial rule, the seed split, the arm choice
(OC-rg over OC), the outcome classes and the vendor price list all come from
analysis/paper_numbers.py, which in turn builds on analysis/main_table.py; the arm labels and
the exclusion flag are the ones analysis/extract_trials.py wrote into trials.csv.  This script
only groups and formats.

  A1  tableA1_coverage.tex     coverage matrix: one row per model x subset x harness x run,
                               with the contributing jobs, tasks attempted / usable / void.
  A2  tableA2_denominators.tex denominator ledger 500 -> 492 -> 45 + 447, then the per-arm
                               counts of void / overflow / timeout / step-cap / output cut
                               over the canonical run-1 trials.
  A10 tableA10_sensitivity.tex the four sensitivity variants of every main paired contrast.

Facts that cannot be derived from trials.csv (missing arms, GLM smoke rounds absent from
trials.csv, ...) are written into the table footnotes below by hand.

Run: python3 analysis/tab_appendix.py        -> paper/latex/tables/tableA{1,2,10}.tex
Read-only w.r.t. the data; stdlib only.
"""
import os
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import main_table as mt            # noqa: E402  canonical rule, INFRA/usable, wilson
import paper_numbers as pn         # noqa: E402  canonical_by_seed, pick_arm, paired, PRICES, outcome

TDIR = os.path.normpath(os.path.join(HERE, "..", "paper", "latex", "tables"))
MODELS = pn.MODELS                                    # figstyle.MODEL_ORDER, same list
MSHORT = {"qwen3.6-35b-a3b": "Qwen3.6", "qwen3.8-27b": "Qwen3.8", "ds-v4-flash": "DS Flash",
          "glm-5.3-flash": "GLM Flash", "hy4-preview": "HY4", "opus5": "Opus 5"}
HSH = pn.H_SHORT
TARGET = {"hard45": 45, "pool447": 447}
DASH = "---"
SAME = object()            # variant defined but drops nothing: identical to the baseline
TIMEOUT_EXC = {"SoftTimeout", "AgentTimeoutError"}
STEPCAP_EXC = {"StepCapReached"}
OUTCUT_EXC = {"OutputTokenExceededError"}


# ----------------------------------------------------------------------------- helpers
def tt(s):
    """Job names in \\texttt with a break opportunity after every hyphen."""
    return r"\texttt{" + s.replace("-", r"-\allowbreak ") + "}"


def ci(lo, hi):
    return f"[{lo:+.1f}, {hi:+.1f}]"


def wrap(lines, small=True):
    body = "\n".join(lines) + "\n"
    return ("{\\small\\setlength{\\tabcolsep}{3.5pt}\n" + body + "}\n") if small else body


def write(name, lines, small=True):
    os.makedirs(TDIR, exist_ok=True)
    path = os.path.join(TDIR, name)
    with open(path, "w") as fh:
        fh.write("% generated by analysis/tab_appendix.py -- do not edit\n")
        fh.write(wrap(lines, small))
    print("wrote", path)
    return path


def stem_jobs(jobs, primary=None):
    """'oc-x-nw-rg (+ -r, -r2)' -- the base job as the stem, the reruns as suffixes."""
    jobs = sorted(jobs, key=lambda j: (len(j), j))
    if not jobs:
        return DASH
    if primary in jobs:
        jobs = [primary] + [j for j in jobs if j != primary]
    stem, rest = jobs[0], jobs[1:]
    out = tt(stem)
    if rest:
        parts = [tt(j[len(stem):]) if j.startswith(stem) else tt(j) for j in rest]
        out += r" \,{\scriptsize(+ " + ", ".join(parts) + ")}"
    return out


# ----------------------------------------------------------------------------- data
rows, _fields = mt.load(mt.CSV_PATH)
cells = pn.canonical_by_seed(rows)
CUT = pn.load_cutoff_terminals(pn.CUTOFF_TXT)

# jobs of an arm, per seed.  A job's 'repeat' is its seed except in the k=2 jobs, which pack
# both seeds into one repeat=1 job; those are listed under every seed they supplied a row to.
jobs_by_arm = defaultdict(lambda: defaultdict(set))       # (lab, model, subset) -> seed -> {job}
LAB_OF = {(h, a): lab for lab, h, a in mt.COLS}           # (harness, arm) -> column label
for r in rows:
    if r.get("exclude") == "1":
        continue
    lab = LAB_OF.get((r.get("harness"), r.get("arm")))
    if lab is None or r.get("model") not in MODELS or r.get("subset") not in pn.SUBSETS:
        continue
    jobs_by_arm[(lab, r["model"], r["subset"])][int(mt.num(r.get("repeat")) or 1)].add(r["job"])
for cell, per_seed in cells.items():                      # k=2 jobs and repairs, per canonical row
    for sd, d in per_seed.items():
        for r in d.values():
            jobs_by_arm[cell][sd].add(r["job"])


def arm_rows(model, subset, harness, lab=None):
    """seed -> {task: canonical row} for the canonical arm (or a named label)."""
    if lab is None:
        lab, c = pn.pick_arm(cells, model, subset, harness)
        return lab, (c or {})
    return lab, cells.get((lab, model, subset), {})


def cls(r):
    """outcome class, with paper_numbers.outcome's 'cap' split into timeout / step-cap / cut."""
    o = pn.outcome(r, CUT)
    if o != "cap":
        return o
    exc = r.get("exception_type") or ""
    if exc in TIMEOUT_EXC:
        return "timeout"
    if exc in STEPCAP_EXC:
        return "stepcap"
    if exc in OUTCUT_EXC:
        return "cutoff"
    return "othercap"


# ============================================================================= A1 coverage
def table_a1():
    L = [r"\begin{tabular}{@{}lllcrrrrl p{3.0cm}@{}}", r"\toprule",
         r"Model & Subset & Arm & Run & $n$ & ok & pass & void & Status & Jobs \\",
         r"\midrule"]
    prev_m = prev_s = None
    for m in MODELS:
        for s in pn.SUBSETS:
            for h in pn.HARNESSES:
                lab, c = arm_rows(m, s, h)
                if not c:
                    continue
                for sd in sorted(c):
                    d = c[sd]
                    n, u = len(d), len(mt.usable(d))
                    void = n - u
                    tgt = TARGET[s]
                    status = "complete" if u >= tgt else f"partial ({u}/{tgt})"
                    js = sorted(jobs_by_arm[(lab, m, s)].get(sd, set())
                                or {r["job"] for r in d.values()})
                    seen = defaultdict(int)
                    for r in d.values():
                        seen[r["job"]] += 1
                    prim = max(seen, key=lambda j: (seen[j], -len(j))) if seen else None
                    mcell = MSHORT[m] if m != prev_m else ""
                    scell = s if (m, s) != (prev_m, prev_s) else ""
                    L.append(f"{mcell} & {scell} & {lab} & {sd} & {n} & {u} & {mt.passes(mt.usable(d))} & {void} & "
                             f"{status} & {stem_jobs(js, prim)} \\\\")
                    prev_m, prev_s = m, s
        L.append(r"\addlinespace")
    L += [r"\bottomrule",
          r"\multicolumn{10}{@{}p{\linewidth}@{}}{\footnotesize Arms: \emph{CC} = Claude Code, "
          r"\emph{mini} = mini-SWE-agent, \emph{OC} = OpenCode as shipped, \emph{OC-rg} = OpenCode "
          r"with ripgrep pre-placed (the canonical OpenCode arm wherever it exists).  "
          r"Not-excluded jobs only; smoke and "
          r"crashed batches carry \texttt{exclude=1} in \texttt{analysis/extract\_trials.py} and "
          r"never enter a cell.  \emph{Run}: the job-level repeat, except in the Qwen3.8 hard45 "
          r"and Qwen3.6/3.8 $k{=}2$ jobs, where the within-job attempt index is the run index, so one "
          r"job appears under both runs.  \emph{void} = scored trial lost to one of the 14 infra "
          r"exception types (\texttt{main\_table.INFRA}); the task is then absent from the paired "
          r"analyses.  Arms outside the main grid --- "
          r"\texttt{nothink}, \texttt{midsys}, \texttt{c2-*}, \texttt{cc-v1.0.100}, the "
          r"\texttt{dsh} harness and every web-enabled arm --- are excluded from this matrix and "
          r"reported in their own appendix sections.} \\",
          r"\end{tabular}"]
    return write("tableA1_coverage.tex", L)


# ============================================================================= A2 denominators
def table_a2():
    L = [r"\begin{tabular}{@{}lllrrrrrrrrl@{}}", r"\toprule",
         r"\multicolumn{12}{@{}p{\linewidth}@{}}{\emph{(a) Denominator ledger}} \\",
         r"\multicolumn{12}{@{}p{\linewidth}@{}}{SWE-bench Verified: \textbf{500} tasks} \\",
         r"\multicolumn{12}{@{}p{\linewidth}@{}}{\quad $-$ 8 \texttt{psf/requests} instances "
         r"(verifier depends on \texttt{httpbin.org}, hangs offline) $\rightarrow$ "
         r"\textbf{pool492} $=$ 492} \\",
         r"\multicolumn{12}{@{}p{\linewidth}@{}}{\quad $\rightarrow$ \textbf{hard45} $=$ 45 "
         r"(whole difficulty bands 1--4\,h and $>$4\,h: 42 $+$ 3; zero sampling degrees of "
         r"freedom) $+$ \textbf{pool447} $=$ 447 (the complementary remainder, disjoint)} \\",
         r"\multicolumn{12}{@{}p{\linewidth}@{}}{\quad \texttt{django\_\_django-11133} is filed under the "
         r"hard45 label as the universal smoke task but belongs to pool447; it has no usable "
         r"hard45 row, so the scored hard45 universe is 45.} \\",
         r"\addlinespace",
         r"\multicolumn{12}{@{}p{\linewidth}@{}}{\emph{(b) What the denominator loses, canonical run-1 trials}} \\",
         r"\addlinespace",
         r"Subset & Model & Arm & $n$ & ok & void & overfl. & t/out & step & out-cut & other & \\",
         r"\midrule"]
    for s in pn.SUBSETS:
        prev_m, first_row = None, True
        for m in MODELS:
            for h in pn.HARNESSES:
                lab, c = arm_rows(m, s, h)
                d = (c or {}).get(mt.MAIN_SEED)
                if not d:
                    continue
                cnt = defaultdict(int)
                for r in d.values():
                    cnt[cls(r)] += 1
                L.append(f"{s if first_row else ''} & {MSHORT[m] if m != prev_m else ''} & "
                         f"{HSH[h]}{'-rg' if lab == 'OC-rg' else ''} & {len(d)} & "
                         f"{len(mt.usable(d))} & {cnt['void']} & {cnt['overflow']} & "
                         f"{cnt['timeout']} & {cnt['stepcap']} & {cnt['cutoff']} & "
                         f"{cnt['othercap']} & \\\\")
                prev_m, first_row = m, False
        L.append(r"\addlinespace")
    L += [r"\bottomrule",
          r"\multicolumn{12}{@{}p{\linewidth}@{}}{\footnotesize Classes follow "
          r"\texttt{analysis/paper\_numbers.py:outcome()} on the canonical run-1 trial of every "
          r"task.  \emph{void} = infra exception (not scored as an outcome, removed from the "
          r"denominator); \emph{overflow} = \texttt{ContextWindowExceeded} or the extractor's "
          r"context-overflow flag; \emph{timeout} = \texttt{SoftTimeout} / "
          r"\texttt{AgentTimeoutError}; \emph{step-cap} = \texttt{StepCapReached}; "
          r"\emph{out-cut} = the run ended on the 32\,k output-token ceiling (OpenCode: a "
          r"terminal \texttt{step\_finish} with \texttt{reason=length}, from "
          r"\texttt{analysis/cutoff\_audit.txt}; Claude Code: a fatal "
          r"\texttt{OutputTokenExceededError}).  Overflow, timeout, step-cap and out-cut trials "
          r"are \emph{kept} and scored as failures in every main table; column (b) says how many "
          r"they are.  \emph{other} = \texttt{NonZeroAgentExitCodeError}, the remaining member "
          r"of the cap set \texttt{paper\_numbers.CAP\_EXC}.  The wall-clock limit is not "
          r"symmetric on the locally served Qwen arms: the six OpenCode timeouts on "
          r"Qwen3.8-27B $\times$ hard45 are a 5{,}760\,s limit against Claude Code's 36{,}000\,s "
          r"on the same model, and all six were still making tool calls, with a patch already on "
          r"disk, when they were stopped (none near the 300-step cap).} \\",
          r"\end{tabular}"]
    return write("tableA2_denominators.tex", L)


# ============================================================================= A10 sensitivity
def _restrict(d1, d2, drop):
    ts = {t for t in set(d1) | set(d2) if t in drop}
    return ({t: r for t, r in d1.items() if t not in ts},
            {t: r for t, r in d2.items() if t not in ts})


def _var_cell(res, base):
    if res is SAME:
        return r"$=$", None
    if res is None or not res.get("n"):
        return DASH, None
    n_b = base["n"] if isinstance(base, dict) else None
    tag = "" if res["n"] == n_b else f"$^{{\\scriptscriptstyle {res['n']}}}$"
    return f"{res['diff_pp']:+.1f}{tag}", res


def table_a10():
    L = [r"\begin{tabular}{@{}llrrrrr@{}}", r"\toprule",
         r"Model & Pair & \multicolumn{1}{c}{baseline $\Delta$ (pp) [95\% CI] ($n$)} & "
         r"no ovfl. & per-prot. & OC ship & run 2 \\", r"\midrule"]
    flagged = []
    prev = None
    for s in pn.SUBSETS:
        L.append(r"\multicolumn{7}{@{}l}{\emph{" + s + r"}} \\")
        for m in MODELS:
            for h1, h2 in pn.PAIRS:
                lab1, c1 = arm_rows(m, s, h1)
                lab2, c2 = arm_rows(m, s, h2)
                d1 = (c1 or {}).get(mt.MAIN_SEED)
                d2 = (c2 or {}).get(mt.MAIN_SEED)
                if not d1 or not d2:
                    continue
                u1, u2 = mt.usable(d1), mt.usable(d2)
                base = pn.paired(u1, u2)
                if not base.get("n"):
                    continue
                # (i) overflow-excluded
                ovf = {t for d in (d1, d2) for t, r in d.items() if cls(r) == "overflow"}
                a, b = _restrict(u1, u2, ovf)
                v_ovf = pn.paired(a, b) if ovf else SAME
                # (ii) per-protocol: drop cap / timeout / void tasks in either arm
                bad = {t for d in (d1, d2) for t, r in d.items()
                       if cls(r) in ("void", "timeout", "stepcap", "othercap", "cutoff")}
                a, b = _restrict(u1, u2, bad)
                v_pp = pn.paired(a, b) if bad else SAME
                # (iii) OC as-shipped in place of OC-rg
                v_oc = None
                if "opencode" in (h1, h2) and "OC-rg" in (lab1, lab2):
                    alt = cells.get(("OC", m, s), {}).get(mt.MAIN_SEED)
                    if alt and mt.usable(alt):
                        au = mt.usable(alt)
                        v_oc = pn.paired(au if h1 == "opencode" else u1,
                                         au if h2 == "opencode" else u2)
                # (iv) run 2 in place of run 1
                s1 = (c1 or {}).get(2)
                s2 = (c2 or {}).get(2)
                v_sd = None
                mixed = False
                if s1 or s2:
                    a = mt.usable(s1) if s1 else u1
                    b = mt.usable(s2) if s2 else u2
                    mixed = not (s1 and s2)
                    v_sd = pn.paired(a, b)
                cell_ovf, r_ovf = _var_cell(v_ovf, base)
                cell_pp, r_pp = _var_cell(v_pp, base)
                cell_oc, r_oc = _var_cell(v_oc, base)
                cell_sd, r_sd = _var_cell(v_sd, base)
                if mixed and r_sd:
                    cell_sd += r"$^{\ast}$"
                pair = f"{HSH[h1]}$-${HSH[h2]}"
                mcell = MSHORT[m] if (m, s) != prev else ""
                L.append(f"{mcell} & {pair} & {base['diff_pp']:+.1f} "
                         f"{{\\scriptsize {ci(*base['ci95_pp'])} ({base['n']})}} & "
                         f"{cell_ovf} & {cell_pp} & {cell_oc} & {cell_sd} \\\\")
                prev = (m, s)
                for nm, rr in (("overflow-excl", r_ovf), ("per-protocol", r_pp),
                               ("OC as-shipped", r_oc), ("run 2", r_sd)):
                    if rr is None:
                        continue
                    dd = rr["diff_pp"] - base["diff_pp"]
                    sign = (abs(base["diff_pp"]) > 0.05 and abs(rr["diff_pp"]) > 0.05
                            and (rr["diff_pp"] > 0) != (base["diff_pp"] > 0))
                    if sign or abs(dd) >= 5.0:
                        flagged.append((m, s, f"{HSH[h1]}-{HSH[h2]}", nm, base["diff_pp"],
                                        rr["diff_pp"], rr["n"], "sign" if sign else "", dd))
            if prev == (m, s):
                L.append(r"\addlinespace")
    L += [r"\bottomrule",
          r"\multicolumn{7}{@{}p{\linewidth}@{}}{\footnotesize Every cell is the paired "
          r"difference (first harness $-$ second) over the tasks both arms scored, computed by "
          r"\texttt{paper\_numbers.paired} on the canonical trials; the baseline column is the "
          r"number in Fig.~1b / Table~2 (intention-to-treat: overflow, cap and cut trials all "
          r"count as failures).  \emph{no ovfl.}: tasks where either arm hit the context "
          r"window are dropped.  \emph{per-prot.} (per protocol): tasks where either arm ended on a step "
          r"cap, a timeout, an output cut or an infra void are dropped.  $=$ marks a variant "
          r"that is defined but drops no task, i.e. reproduces the baseline exactly.  "
          r"\emph{OC ship}: "
          r"the as-shipped OpenCode arm (no pre-placed ripgrep) replaces OC-rg.  \emph{run 2}: the "
          r"second independent run replaces run 1.  \emph{---} means the variant does not "
          r"exist for that cell (no such trial, no as-shipped arm, no second run).  "
          r"$^{\ast}$ only one of the two arms has a second run; the other stays at run 1.  "
          r"A superscript is the variant's $n$ where it differs from the baseline's.} \\",
          r"\end{tabular}"]
    return write("tableA10_sensitivity.tex", L), flagged


# ============================================================================= main
def main():
    p1 = table_a1()
    p2 = table_a2()
    (p10, flagged) = table_a10()
    print()
    print("sensitivity cells that flip sign or move >= 5 pp vs baseline:")
    for m, s, pair, nm, b, v, n, sg, dd in flagged:
        print(f"  {m:16s} {s:8s} {pair:9s} {nm:14s} base={b:+6.1f} -> {v:+6.1f} (n={n}, d={dd:+.1f}) {sg}")
    return [p1, p2, p10]


if __name__ == "__main__":
    main()
